import Header from "@/components/Header";
import { barlow, berlinSans } from "./fonts";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${berlinSans.variable} ${barlow.variable}`}>
      <body className={`${barlow.className} overflow-x-hidden bg-dark-clr text-white`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
